language: node_js
node_js:
  - "0.10"
before_install:
- npm install npm@2.8.2 -g
env:
# Get some of them configs
- HYPERBAHN_REMOTE_TEST_CONFIG=
- HYPERBAHN_REMOTE_TEST_CONFIG=test/config/with_lazy_relay.json
- HYPERBAHN_REMOTE_TEST_CONFIG=test/config/with_peer_heap.json
- HYPERBAHN_REMOTE_TEST_CONFIG=test/config/with_partial_affinity.json
script: npm run travis
